name: Update from upstream

on:
  workflow_dispatch:

  push:
    branches: 
      - master
    paths:
      - '.github/workflows/Update.yml'

  schedule:
    - cron: "0 0 */5 * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.REPO_TOKEN }}
    - name: Update from upstream
      run: |
        docker pull teddysun/shadowsocks-libev:latest > /tmp/msg
        u_hash=$(cat /tmp/msg | grep Digest: | sed "s/Digest: sha256://")
        [ $u_hash ] && sed -i "s/^ARG UPSTEAM_HASH=.*/ARG UPSTEAM_HASH=$u_hash/g" Dockerfile
    - name: Push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update Shadowsocks-libev
        skip_dirty_check: false
